#!/usr/bin/env bash
#Install nginx web server

# Updating and installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allowing nginx on firewall
sudo ufw allow "Nginx HTTP"

# Creating new index
echo 'Hello World!' > /var/www/html/index.html

# Starting nginx
sudo service nginx start
