#!/usr/bin/env bash
# Install nginx on your web-01 server
# Configures a new ubuntu machine by installing
# Serve a page that would return a Hello World string

# Updating and installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allowing nginx on firewall
sudo ufw allow "Nginx HTTP"

# Create a directory for hosting website files
mkdir -p /var/www/html/

# Set permissions recursively to 755 for the /var/www directory
sudo chmod -R 755 /var/www

# Creating new index
echo 'Hello World!' > /var/www/html/index.html

# Define the Nginx server configuration as a variable
SERVER_CONFIG="server {
	listen 80 default_server;
	root /var/www/html;
	index index.html;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.alxafrica.com permanent;
	}
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# Check if Nginx is running, start it if it's not, otherwise restart it
if [ "$(pgrep -c nginx)" -le 0 ]
then
	service nginx start
else
	service nginx restart
fi
