#!/usr/bin/env bash
#Install nginx web server

# Updating and installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allowing nginx on firewall
sudo ufw allow "Nginx HTTP"

# Creating new index
echo 'Hello World!' > /var/www/html/index.html

# Creating custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configuring Nginx
printf %s "server {
    listen 80 default_server; # Listen on port 80
    listen [::]:80 default_server; # IPv6 support
    add_header X-Served-By \$HOSTNAME; # Add a custom header with server hostname
    root   /var/www/html; Root directory for web server
    index  index.html; # Default index file

    location /redirect_me {   # Redirect location
        return 301 https://github.com/essaket/;  # Redirect to github.com/essaket/
    }

    error_page 404 /404.html; # Custom error page for 404
    location /404 {  # Location for 404 errors
      root /var/www/html;  # Serve 404 page from /var/www/html
      internal;  # Only accessible internally
    }
}" > nginx-sites-enabled_default /etc/nginx/sites-available/default  # write server configuration to Nginx config file

# Starting nginx
sudo service nginx start
