#!/usr/bin/env bash
# Install nginx web server

# Updating and installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allowing nginx on firewall
sudo ufw allow "Nginx HTTP"

# Creating new index
echo 'Hello World!' > /var/www/html/index.html

# Creating custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configuring Nginx
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

# Starting nginx
sudo service nginx start
