#!/usr/bin/env bash
#Install nginx web server

# Updating and installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allowing nginx on firewall
sudo ufw allow "Nginx HTTP"

# Creating new index
echo 'Hello World!' > /var/www/html/index.html

# Creating custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configuring Nginx
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

server_config=\
"server {
                listen 80 default_server;
                listen [::]:80 default_server;
                root /var/www/html;
                index index.html
                server_name_;
                add_header X-Served-By \$hostname;
                location / {
                        try_files \$uri \$uri/ =404;
                }
                if (\$request_filename ~ redirect_me){
                        rewrite ^ https://www.alxafrica.com/ permanent;
                }
                error_page 404 /error_404.html;
                location = /error_404.html {
                        internal;
                }
}"

#shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

# Starting nginx
sudo service nginx start
