#!/usr/bin/env bash
# This script configures an Nginx server to listen on port 80

# Remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
service nginx restart
