#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.
# a different way using ifconfig:
#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'
#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
#ifconfig | grep -o -P '(?<=inet addr:).*?(?=\s)'

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
